### DISCUSSION TITLE
Not Compatible with HVCI (Core Isolation)

### DISCUSSION THREAD

**Discussion by DastardlyDino** [tnodir/fort#108] [Q&A] [answered]
Cannot install this program. I get an error message that says "This program is not compatible with HVCI (Core Isolation)."

**Comment by tnodir** [comment, marked as answer]
Yes, you have to disable the Core Isolation to run this program.

See https://www.tomshardware.com/how-to/disable-vbs-windows-11

**Reply by eabase** [reply]
@tnodir 
I would like to add that the instructions on *Eleven Forum* and *Toms Hardware* is are out of date, and may be misleading, at least for `W11 Pro (24H2+)`. 

When you open the **Privacy & security >> Windows Security >> Device security** tab from "Settings", you will see something different when selecting. 

---

<img width="994" height="663" alt="2026-0121_161253_Windows_Security" src="https://github.com/user-attachments/assets/6d03ee34-e5d8-4ef5-9057-5b10d33d4115" />


---

> [!CAUTION]
> **"Device security"** now depends on 4 other sub-settings.
> If **any* of those are enabled, the *system info** will still show `Virtualization-based security: Running`, regardless if mentioned Registry setting is set to disabled. 
> `[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity]`)


- [ ] `Memory integrity`
- [ ] `Kernel-mode Hardware-enforced Stack protection`
- [x] `Local authority protection`
- [ ] `Microsoft Vulnerable Driver Blacklist`

In addition, the other "solution", for the above problem, was to remove the **"Virtual Machine Platform"** Windows feature. This is just dumb as it would render your PC useless for most development scenarios, because that would also **prevent you from using all of these**:

- Any PC Virtualization support to run virtual machines
- Using  `Windows Subsystem for Linux (WSL)` and 
- Using `Docker` as it also depends on WSL.
- Using `QEMU` ? - IDK ...
- Creation of some MSIX app packages for an MSI or App-V.



```yaml
# systeminfo.exe

...
Virtualization-based security: Status: Running              <------------- THIS !!
                               Required Security Properties:
                               Available Security Properties:
                                     Base Virtualization Support
                                     Secure Boot
                                     DMA Protection
                                     Secure Memory Overwrite
                                     UEFI Code Readonly
                                     SMM Security Mitigations 1.0
                                     Mode Based Execution Control
                                     APIC Virtualization
                               Services Configured:
                               Services Running:
                               App Control for Business policy: Enforced
                               App Control for Business user mode policy: Off
                               Security Features Enabled:
Hyper-V Requirements:          A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

---

<img width="1017" height="1255" alt="2026-0121_161343_Windows_Security" src="https://github.com/user-attachments/assets/3f159751-86ab-473c-ac00-ed8826d4c04a" />

---

So yeah, it seem that you need to turn OFF all 4 of the above, but this need further testing, I guess?
